# Strict Clippy configuration
# Note: Most lints are configured in Cargo.toml [lints] section
# This file is for Clippy-specific configuration parameters

# Disallow unwrap/expect except in tests
allow-unwrap-in-tests = true
allow-expect-in-tests = true

# Maximum complexity thresholds
cognitive-complexity-threshold = 100
too-many-lines-threshold = 500
type-complexity-threshold = 500

# Enforce documentation
missing-docs-in-crate-items = true