name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  build-release:
    name: Build Release
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows, macos]
        include:
        - build: linux
          os: ubuntu-latest
          rust: stable
          target: x86_64-unknown-linux-gnu
          archive-name: greedytile-linux.tar.gz
        - build: windows
          os: windows-latest
          rust: stable
          target: x86_64-pc-windows-msvc
          archive-name: greedytile-windows.zip
        - build: macos
          os: macos-latest
          rust: stable
          target: x86_64-apple-darwin
          archive-name: greedytile-macos.tar.gz
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}
    
    - name: Build Release Binary
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Create Archive (Linux/macOS)
      if: matrix.build != 'windows'
      run: |
        staging="greedytile-${{ github.ref_name }}-${{ matrix.target }}"
        mkdir -p "$staging"
        cp target/${{ matrix.target }}/release/greedytile "$staging/"
        cp README.md LICENSE* "$staging/" || true
        tar czf "${{ matrix.archive-name }}" "$staging"
        echo "ASSET=${{ matrix.archive-name }}" >> $GITHUB_ENV
    
    - name: Create Archive (Windows)
      if: matrix.build == 'windows'
      shell: pwsh
      run: |
        $staging = "greedytile-${{ github.ref_name }}-${{ matrix.target }}"
        New-Item -ItemType Directory -Force -Path $staging
        Copy-Item "target/${{ matrix.target }}/release/greedytile.exe" -Destination $staging
        Copy-Item "README.md" -Destination $staging -ErrorAction SilentlyContinue
        Get-ChildItem "LICENSE*" | Copy-Item -Destination $staging -ErrorAction SilentlyContinue
        Compress-Archive -Path $staging -DestinationPath "${{ matrix.archive-name }}"
        echo "ASSET=${{ matrix.archive-name }}" >> $env:GITHUB_ENV
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ${{ env.ASSET }}
        asset_name: ${{ env.ASSET }}
        asset_content_type: application/octet-stream